version: '3.7'

services: 
    backend:
        build: .
        restart: 'always'
        ports:
            - '3000:3000'
        environment: 
            - DATABASE_URL=${DATABASE_URL}

    db:
        image: mongo
        restart: 'always'
        ports:
            - '27017:27017'